@extends('layouts.app')
@section('title', 'Transactions · Korina Salon')
@section('content')
<p class="page-kicker">Salon ledger</p><h1>Transactions & commissions</h1><p class="page-subtitle">Record each beautiful result, with staff earnings calculated for you.</p>
<div class="card"><form method="POST" action="{{ route('transactions.store') }}" class="grid" id="transaction-form">@csrf <select name="service_id" id="service" required><option value="">Choose a service</option>@foreach($services as $service)<option value="{{ $service->id }}" data-price="{{ $service->price }}">{{ $service->name }} — ₱{{ number_format($service->price,2) }}</option>@endforeach</select><select name="staff_id" required><option value="">Choose a stylist</option>@foreach($staff as $member)<option value="{{ $member->id }}">{{ $member->name }}</option>@endforeach</select><select name="payment_mode" id="payment-mode" required><option value="Cash">Cash</option><option value="GCash">GCash</option></select><input type="hidden" name="gcash_confirmed" id="gcash-confirmed" value="0"><button type="submit">Record transaction</button></form><p id="gcash-note" style="display:none;margin:15px 0 0;color:#0874d1;font-size:13px;font-weight:700">GCash demo selected — the payment simulation will open before recording.</p></div>
<div class="section-heading"><h2>Transaction history</h2><p>{{ $transactions->count() }} recorded sale{{ $transactions->count() === 1 ? '' : 's' }}</p></div><div class="card table-card"><table><tr><th>Service</th><th>Staff</th><th>Payment</th><th>Amount</th><th>Commission</th></tr>@forelse($transactions as $transaction)<tr><td>{{ $transaction->service->name }}</td><td>{{ $transaction->staff->name }}</td><td><span class="badge">{{ $transaction->payment_mode }}</span></td><td class="amount">₱{{ number_format($transaction->amount,2) }}</td><td>₱{{ number_format($transaction->commission,2) }}</td></tr>@empty<tr><td colspan="5">No transactions have been recorded yet.</td></tr>@endforelse</table></div>
@endsection
@push('modals')
<div class="modal-backdrop" id="gcash-modal" role="dialog" aria-modal="true" aria-labelledby="gcash-title"><div class="payment-modal"><div class="gcash-mark">G</div><p class="page-kicker" style="margin-top:13px">Demo checkout</p><h2 id="gcash-title">Pay with GCash</h2><p>Scan the demo QR code or simulate a payment approval.</p><div class="qr"><span>GCASH DEMO</span></div><p class="payment-total" id="gcash-total">₱0.00</p><p>This is a simulation only. No real GCash account will be charged.</p><div class="modal-actions"><button type="button" class="button-outline" id="gcash-cancel">Cancel</button><button type="button" class="button-gold" id="gcash-confirm">Simulate paid</button></div></div></div>
<script>const form=document.getElementById('transaction-form'),mode=document.getElementById('payment-mode'),note=document.getElementById('gcash-note'),modal=document.getElementById('gcash-modal'),confirmed=document.getElementById('gcash-confirmed');mode.addEventListener('change',()=>{note.style.display=mode.value==='GCash'?'block':'none';if(mode.value!=='GCash')confirmed.value='0'});form.addEventListener('submit',(event)=>{if(mode.value==='GCash'&&confirmed.value!=='1'){event.preventDefault();const option=document.getElementById('service').selectedOptions[0];document.getElementById('gcash-total').textContent=option?.dataset.price?'₱'+Number(option.dataset.price).toLocaleString('en-PH',{minimumFractionDigits:2}):'Select a service first';modal.classList.add('is-open')}});document.getElementById('gcash-cancel').addEventListener('click',()=>modal.classList.remove('is-open'));document.getElementById('gcash-confirm').addEventListener('click',()=>{confirmed.value='1';modal.classList.remove('is-open');form.requestSubmit()});</script>
@endpush
