@extends('layouts.app')
@section('title', 'Schedule · Korina Salon')
@section('content')
<p class="page-kicker">Team calendar</p><div class="page-title-row"><div><h1>Staff schedule</h1><p class="page-subtitle">Peak shifts make holiday and special-occasion coverage visible.</p></div><button type="button" class="add-button" id="assign-shift-button" aria-label="Assign a staff shift">+</button></div>
<div class="card table-card"><table><tr><th>Date</th><th>Staff member</th><th>Specialty</th><th>Start</th><th>End</th><th>Status</th></tr>@forelse($schedules as $shift)<tr><td>{{ $shift->shift_date }}</td><td>{{ $shift->staff->name }}</td><td>{{ $shift->staff->specialty ?? 'Salon Specialist' }}</td><td>{{ $shift->shift_start }}</td><td>{{ $shift->shift_end }}</td><td><span class="badge">{{ $shift->status }}</span></td></tr>@empty<tr><td colspan="6">No shifts scheduled.</td></tr>@endforelse</table></div>
@endsection
@push('modals')
<div class="modal-backdrop" id="assign-shift-modal" role="dialog" aria-modal="true" aria-labelledby="assign-shift-title"><div class="payment-modal schedule-modal"><button type="button" class="modal-close" id="assign-shift-close" aria-label="Close">×</button><p class="page-kicker">Manager & owner tools</p><h2 id="assign-shift-title">Assign a shift</h2><p>Choose a team member, then set their schedule.</p><form method="POST" action="{{ route('schedules.store') }}" class="schedule-form">@csrf <label>Staff member<select name="staff_id" id="schedule-staff" required><option value="">Choose a staff member</option>@foreach($staff as $member)<option value="{{ $member->id }}" data-specialty="{{ $member->specialty ?? 'Salon Specialist' }}">{{ $member->name }}</option>@endforeach</select></label><p class="specialty-note" id="selected-specialty">Specialty will appear here.</p><label>Date<input type="date" name="shift_date" value="{{ today()->format('Y-m-d') }}" required></label><div class="form-row"><label>Start<input type="time" name="shift_start" value="09:00" required></label><label>End<input type="time" name="shift_end" value="18:00" required></label></div><label>Shift type<select name="status" required><option value="Regular">Regular</option><option value="Peak">Peak</option><option value="Day Off">Day Off</option></select></label><button type="submit" class="button-gold">Assign shift</button></form></div></div>
<script>const assignButton=document.getElementById('assign-shift-button'),assignModal=document.getElementById('assign-shift-modal'),assignClose=document.getElementById('assign-shift-close'),scheduleStaff=document.getElementById('schedule-staff'),specialtyNote=document.getElementById('selected-specialty');assignButton.addEventListener('click',()=>assignModal.classList.add('is-open'));assignClose.addEventListener('click',()=>assignModal.classList.remove('is-open'));assignModal.addEventListener('click',(event)=>{if(event.target===assignModal)assignModal.classList.remove('is-open')});scheduleStaff.addEventListener('change',()=>{const specialty=scheduleStaff.selectedOptions[0]?.dataset.specialty;specialtyNote.textContent=specialty?`Specialty: ${specialty}`:'Specialty will appear here.'});</script>
@endpush
